### ISSUE TITLE
License ? composer.json ?

### ISSUE THREAD

**Issue by mcd-php** [balalaikaboy/CassandraPDO4Doctrine#1]
Please specify license for your work, otherwise it's impossible to use or modify in any serious project inside legal field. I think it should be the same as Doctrine itself - MIT.

Please make `composer.json` file for automatic installation: https://getcomposer.org/, [Starting a New PHP Package The Right Way](http://www.sitepoint.com/starting-new-php-package-right-way/), [PHP Package Checklist](http://phppackagechecklist.com).

Re-using vendor namespace is wrong - doing so is like pretending what your code is written by original author and imposing responsibility of your quality upon him.

Modified files should be turned to overrides.

**Comment by balalaikaboy** [comment]
Thanks for your advice. I've been so lazy recently :).Will try to implement what you suggested when I have time.

**Comment by mcd-php** [comment]
Nice to hear good news from you !

You are the only one who can legally apply license to your work, and changing copyrights takes no development effort and poses no risk of introducing errors. So please, copy [LICENSE](https://github.com/doctrine/doctrine2/blob/master/LICENSE) file from Doctrine itself. 

After this, I may add license boilerplate to the top of files like in Doctrine or in Symfony, bulk change namespace and add `composer.json`, so the project will be installable by `composer`.

For namespace - I will just replace `Doctrine` to `CassandraPDO4Doctrine`, are you OK with this ?

P.S. This work is very important for community, since Symfony/Doctrine and Cassandra are both best of their classes. If you have no time to improve, we should promote it to community so someone may adopt.

**Comment by balalaikaboy** [comment]
Hi there,

I have added the MIT license file to the project. Please go ahead with your suggestions. I would be very happy to see this project bringing some value to the community. Your contribution is very much appreciated.
