### ISSUE TITLE
Could you put the content of your Entity\Product.php file?

### ISSUE THREAD

**Issue by akononykhin** [balalaikaboy/CassandraPDO4Doctrine#2]
Hello
Could you put the content of your Entity\Product.php file?
I'm newbie to both Doctrine2 and Cassandra and trying to configure Symfony2/CassandraPDO/Doctine.
I've created test Entity according to Symfone2 Doctrine doc but when trying to get info from Cassandra I receive the next Exception:

[2/2] DBALException: An exception occurred while executing 'SELECT t0.key AS key1, t0.value AS value2 FROM currency t0':

CQLSTATE[HY000] [2] line 1:26 no viable alternative at input 'AS'

currency is my ColumnFamily with two columns - key and value.

Obviously Cassandra doesn't support 'AS' syntax but how can I prevent Doctrine not to use it?

Thanks in advance.

**Comment by balalaikaboy** [comment]
Hi there,

Did you copy CassandraConnection.php (vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOCassandra/CassandraConnection.php) into its corresponding directory? It serves to remove table aliases from the query. Your final query will look like this:
"SELECT key AS key1, value AS value2 FROM currency"

My Product.php is just a normal entity file. There is nothing special to it.

**Comment by akononykhin** [comment]
Hello
Yes, it's there:

/home/symfony/cassandra/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOCassandra

root@d39fbd778f02:/home/symfony/cassandra/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOCassandra# ls -l
total 8
-rw-r--r-- 1 root root 2425 Mar  2 19:22 CassandraConnection.php
-rw-r--r-- 1 root root 2332 Mar  2 19:22 Driver.php

I try to get the list of currencies using findAll():

```
    $repository = $this->getDoctrine()->getRepository('AppBundle:Currency');
    $currencies = $repository->findAll();
```

**Comment by akononykhin** [comment]
I found the reason: I used Caddandra 1.2.x which doesn't support aliases. After I installed Cassandra 2.0.x the query passed.

Could you wrote which Doctring mapping time did you use for 'created' column? When I try to use type=datetime:

```
/**
 * @var string
 *
 * @ORM\Column(name="created", type="datetime")
 */
private $created;
```

Symfony throws the next exception:

Could not convert database value "90725040407-11-16 21:56:16" to Doctrine Type datetime. Expected format: Y-m-d H:i:s

**Comment by akononykhin** [comment]
I've modified DateTimeType.php to fix the exception. Looks like in my environment $str is just the number of milliseconds from the epoch.

```
public function getDateStringFromHex($str)
{
        //$date = unpack('H*', $str);
        //$time = hexdec($date[1]) / 1000;
        $time = $str / 1000;
        $dateStr = date('Y-m-d H:i:s', $time);
        return $dateStr;
}
```

**Comment by balalaikaboy** [comment]
Hello,
I apologize for not being able to reply earlier. We have been restructuring the project to make it separate from Doctrine and support composer. 
Regarding the DateTimeType issue, my fix comes from here: https://github.com/Orange-OpenSource/YACassandraPDO/issues/20. I guess you are using a different PDO build but I haven't been able to test for myself. Anyway, I have modified the getDateStringFromHex() function to include what you suggested, as follows:

```
public function getDateStringFromHex($str)
    {
        if(is_numeric($str)){
            $time = $str / 1000;
            return date('Y-m-d H:i:s', $time);
        }
        else{
            $date = unpack('H*', $str);
            $time = hexdec($date[1]) / 1000;
            return date('Y-m-d H:i:s', $time);
        }
    }
```
